### ISSUE TITLE
ClearAll kaataa pelin

### ISSUE THREAD

**Issue by Rampastring** [Jypeli-JYU/Jypeli#2]
https://svn.cc.jyu.fi/srv/svn/ohjdemot/ohj1/s2018/demot/vast/demo7/AngryLego

Kun tason pääsee läpi, `UusiTaso`-metodissa oleva `ClearAll()`-kutsu aiheuttaa pelin kaatumisen. `Layer.Update`-metodissa tehdyn `Objects.Update` -kutsun yhteydessä muokataan listaa foreachin aikana.

**Comment by roeyskoe** [comment]
Ei vaikuta olevan enää ongelma nykypäivänä.
