### ISSUE TITLE
YesNoWindow, Enter hyväksyy ja Esc hylkää

### ISSUE THREAD

**Issue by ajlakanen** [Jypeli-JYU/Jypeli#24]
Luontevat oletuskontrollit olisivat Enter=Yes, Esc=No. Nyt oletuskontrolleja ei ole tai niitä ei ainakaan ilmoiteta dialogissa.

**Comment by roeyskoe** [comment]
Oletusnäppäimistökontrollit olivat useammalle widgetille vahingossa jääneet pois kommentoiduiksi.

Perinteinen toimintahan tuolle on ollut että Esc hylkää, nuolilla voidaan valita vaihtoehto ja enterillä ottaa se. Defaulttina on kyllä.

Laitan päivityksen tulemaan.
